### ISSUE TITLE
Mild Problem

### ISSUE THREAD

**Issue by Colink02** [NinjonikSVK/IGCMS#3]
So I saw the review referring to a virus within the zip file. Unzipping it in my downloads windows gave me the same warning aswell.
![image](https://user-images.githubusercontent.com/11688661/95703863-0d2f9200-0c15-11eb-8b64-28c6cdf515bd.png)
Not exactly sure what it would be doing in that case for a mailserver but it could make sense in some sort of context. I see it is from another open source project https://github.com/b374k/b374k which also had a similar complaint from 2018. I'd assume you might want to look into the pop.php file and figure out why its detecting remote access although the description of b374k makes sense "This PHP Shell is a useful tool for system or web administrator to do remote management without using cpanel, connecting using ssh, ftp etc."

**Comment by NinjonikSVK** [comment]
Hello,
thank you for reporting this issue.

I am currently working on fixing this problem and removing this pop.php file.

Thank you for contributing in IG CMS project.

Regards,
Ninjonik
