### ISSUE TITLE
Na spigotu píšeš jak to nesmážeš ale smazal jsi to..

### ISSUE THREAD

**Issue by nicomenecthejvedet** [NinjonikSVK/IGCMS#4]
Na spigotu píšeš jak to nesmážeš ale smazal jsi to.. Tož jakto že si to smazal? Moc kritické hodnocení co.. No jo no to je tak když nemáš zkušeností a pouštíš se do něčeho velkeho..

**Comment by NinjonikSVK** [comment]
Neviem, že čo má toto spoločné s issues,
ale ja som to na spigotu nezmazal, kedže to ani nejde.

![image](https://user-images.githubusercontent.com/34453649/96331490-f6969a00-105d-11eb-98de-7519bd58679b.png)

Už to so spigotom riešim a vyzerá to, že sa tam CMS v najbližšej dobre vráti.

S zabanovaným účtom totiž to sa mažú aj všetky resources a to by si mohol vedieť, keď píšeš tento typ issues, buď rád, že som ti to nezamietol ako blbosť, čo nemá s issues čo spoločné.

**Comment by NinjonikSVK** [comment]
> 
> 
> Na spigotu píšeš jak to nesmážeš ale smazal jsi to.. Tož jakto že si to smazal? Moc kritické hodnocení co.. No jo no to je tak když nemáš zkušeností a pouštíš se do něčeho velkeho..

Neviem, že čo má toto spoločné s issues,
ale ja som to na spigotu nezmazal, kedže to ani nejde.

![image](https://user-images.githubusercontent.com/34453649/96331490-f6969a00-105d-11eb-98de-7519bd58679b.png)

Už to so spigotom riešim a vyzerá to, že sa tam CMS v najbližšej dobre vráti.

S zabanovaným účtom totiž to sa mažú aj všetky resources a to by si mohol vedieť, keď píšeš tento typ issues, buď rád, že som ti to nezamietol ako blbosť, čo nemá s issues čo spoločné.

**Comment by nicomenecthejvedet** [comment]
Přiště to napišu jinam, neměl jsem čas. No jo no, s myškou v CMS se většinou banuje. 👍

**Comment by NinjonikSVK** [comment]
![image](https://user-images.githubusercontent.com/34453649/96362641-0af69780-112f-11eb-8dce-31b008891ee8.png)

Už bol môj unban schválený.
